--ÝSTANBULDA YAÞAYIP ÝLÇESÝ 'KADIKÖY' DIÞINDA OLANLARI LÝSTELEYÝNÝZ.
SELECT * FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID=C.CITYID
INNER JOIN DISTRICTS D ON D.ID=C.DISTRICTID
WHERE CT.CITY = 'ÝSTANBUL' AND D.DISTRICT NOT LIKE 'KADIKÖY'
--AYNI SORUYU SUBQUERY YÖNTEMÝYLE
SELECT * FROM CUSTOMERS
WHERE CITYID IN(SELECT ID FROM CITIES WHERE CITY='ÝSTANBUL')
AND DISTRICTID IN (SELECT ID FROM DISTRICTS WHERE DISTRICT='KADIKÖY')

--CITIES TABLOSUNDA "Ankara" KAYDINI  SÝLDÝÐÝMÝZÝ VARSAYALIM BU DURUMDA ÞEHRÝ ANKARA OLAN KULLANICILARIN
--ÞEHIR ALANI BOÞ GELECEKTÝR ÞEHÝR ALANI BOÞ OLAN MÜÞTERÝLEÝR SIRALYAN SORGUYU YAZINIZ.

DELETE FROM CITIES WHERE ID=6
DELETE FROM CITIES WHERE ID=34
SELECT * FROM CUSTOMERS C 
LEFT JOIN CITIES CT ON C.CITYID=CT.ID
WHERE CT.ID IS NULL
--SUBQUERY YÖNTEMÝYLE AYNI SORU
SELECT * FROM CUSTOMERS
WHERE CITYID NOT IN (SELECT ID FROM CITIES)

--ÖNCEKÝ SORUDA CITIES TABLOSUNDAN SÝLMÝÞ OLDUÐUMUZ ANKARA VE ÝSTANBUL KAYITLARINI AYNI 
--ID'LERÝ ALACAK ÞEKÝLDE YENÝDEN INSERT 
SELECT * FROM CITIES--EKSÝK VERÝLERÝ BULMAK ÝÇÝN ÇAÐRILDI

SET IDENTITY_INSERT CITIES ON --ID OTOMATÝK ARTTIÐI ÝÇÝN BU ÝÞLEMLE ID'YÝ KEDNÝMÝZ GÝRMEMÝZ SAÐLANDI.

INSERT INTO CITIES (ID,CITY)
VALUES(6,'ANKARA')--ANKARA GERÝ EKLENDÝ CITIES TABLOMUZA


INSERT INTO CITIES (ID,CITY)
VALUES(34,'ÝSTANBUL')--ÝSTANBUL GERÝ EKLENDÝ CITIES TABLOMUZA