--HER ÞEHÝRDE BULUNAN ERKEK VE KADIN SAYISI
SELECT CITY AS SEHIRADI,
(SELECT COUNT(*) FROM CUSTOMERS  C WHERE CT.ID=C.CITYID AND GENDER ='E') as ERKEKSAYISI,
(SELECT COUNT(*) FROM CUSTOMERS  C WHERE CT.ID=C.CITYID AND GENDER ='k') AS KADINSAYISI
FROM CITIES CT

-- CUSTOMERS TABLOSUNA AGEGROUP	ÝSÝMLÝ VERÝTÝPÝ VARCHAR OLAN YENÝ BÝR COLON 
ALTER TABLE CUSTOMERS add AGEGROUP varchar(50)
--bir önceki iþlemde eklenen AGEGROUP alanýný 20-35, 36-45, 46-55 ve 55-60 yaþ aralýðý
--olarak güncelle

UPDATE CUSTOMERS SET AGEGROUP='20-35 YAÞ'
WHERE DATEDIFF(YEAR, BIRTHDATE,GETDATE()) BETWEEN 20 AND 35

UPDATE CUSTOMERS SET AGEGROUP='36-45 YAÞ'
WHERE DATEDIFF(YEAR, BIRTHDATE,GETDATE()) BETWEEN 36 AND 45

UPDATE CUSTOMERS SET AGEGROUP='46-55 YAÞ'
WHERE DATEDIFF(YEAR, BIRTHDATE,GETDATE()) BETWEEN 46 AND 55

UPDATE CUSTOMERS SET AGEGROUP='56-65 YAÞ'
WHERE DATEDIFF(YEAR, BIRTHDATE,GETDATE()) BETWEEN 56 AND 65

UPDATE CUSTOMERS SET AGEGROUP='65 YAÞ ÜSTÜ'
WHERE DATEDIFF(YEAR, BIRTHDATE,GETDATE()) > 65

SELECT 
*,DATEDIFF(YEAR, BIRTHDATE,GETDATE())
 FROM CUSTOMERS
 

 --YAÞ ARALIÐINA GÖRE MÜÞTERÝ SAYISI NOT:AGEGROUP ALANI KULLANILMADAN
SELECT AGEGROUP,COUNT(*) FROM CUSTOMERS GROUP BY AGEGROUP ORDER BY AGEGROUP--GROUP  BY KULLANILARAK

SELECT AGEGROUP2,COUNT(TMP.ID) AS CUSTOMERCOUNT FROM
(
SELECT *, 
CASE 
		WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35 YAÞ ARASI'
		WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45 YAÞ ARASI'
		WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55 YAÞ ARASI'
		WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 56 AND 65 THEN '56-65 YAÞ ARASI'
		WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) >65 THEN '65 YAÞ üstü'
END AGEGROUP2
FROM CUSTOMERS
)TMP
GROUP BY AGEGROUP2
ORDER BY AGEGROUP2
 

